

DROP TABLE IF EXISTS flowers CASCADE;
DROP TABLE IF EXISTS weather;

CREATE TABLE flowers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    temperature TEXT NOT NULL,
    water TEXT NOT NULL,
    weather TEXT NOT NULL

);

-- CREATE TABLE weather (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
-- daily INTEGER NOT NULL,
--     weather_id BIGINT REFERENCES flowers(id)
-- );
CREATE TABLE weather (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    daily INTEGER NOT NULL,
    weather_id  BIGINT REFERENCES flowers(id)
);
