
DROP TABLE IF EXISTS families CASCADE;
DROP TABLE IF EXISTS pets;

CREATE TABLE families (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  house TEXT NOT NULL,
  members INT NOT NULL
);

CREATE TABLE pets (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  name TEXT NOT NULL, 
  color TEXT,
  family_id BIGINT REFERENCES families(id)
  
)
